### ISSUE TITLE
Support namespaced JS interop modules

### ISSUE THREAD

**Issue by pulyaevskiy** [mbullington/node_preamble.dart#4]
Wondering if I could get some help with this issue I just discovered.

I just used `dart_js_facade_gen` to generated Dart facade for Firestore NodeJS package (type definitions from [here](https://github.com/googleapis/nodejs-firestore/tree/master/types)). Produced output looks like this:

```dart
@JS("FirebaseFirestore.setLogFunction")
external void setLogFunction(void logger(String msg));

@JS("FirebaseFirestore.Firestore")
class Firestore {
  external factory Firestore([dynamic options]);
  // et cetera...
}
```

So everything is namespaced under `FirebaseFirestore` and it makes it problematic to use these classes in Node. If I try to create an instance of `Firestore` class, I'd get this:

```
/Users/anatoly/Projects/firestore/build/node/index.dart.js:1967
      new self.FirebaseFirestore.Firestore();
                                ^
TypeError: Cannot read property 'Firestore' of undefined
```

Now, obvious workaround here would be to just allow something like this in the preamble:

```
self.FirebaseFirestore = require('@google-cloud/firestore');
```

But:

1. Is this a good/bad practice?
2. Would require some reflection on imported libraries during build to collect all Node modules which must be `require`d this way. Most likely based on an annotation, e.g.

```dart
@NodeRequire("FirebaseFirestore", "@google-cloud/firestore")
library firestore;

// all the interface definitions go here.
```

I'm not super scared of (2), should be able to implement in `node_interop`. 
But curious if I'm missing something here or maybe there is a better way to achieve this?

From this package it would require another argument to `getPreamble` function, e.g.:

```dart
// New argument is a Map of namespace name to Node package name
String getPreamble(requireModules: { 'FirebaseFirestore': '@google-cloud/firestore' });
```

Also, I'd like to tag someone from JS interop authors. 
@kevmoo wondering if you can recommend a good point of contact?

**Comment by mbullington** [comment]
I'd be okay with adding this if you believe it's the best way to achieve the issue of requiring packages. I've actually thought about this issue multiple times.

I'd assume the only other viable option would be using the dart:js library to require packages at runtime, for example...

```
context["FirebaseFirestore"] = context.callMethod("require", ["@google-cloud/firestore"]);
```

If you feel the preamble is the best way, I don't have any objections to it, but it may need more discussion first.

**Comment by pulyaevskiy** [comment]
I would definitely Iike to get more opinions on this first, before taking any action.

Personally I’d leave preamble as simple as possible, but I thought I’d mention this approach as a conversation starter, and also I couldn’t think of any other alternative.

I like your suggestion about using context object, will definitively try it out tonight and see how/if it works.

Also waiting on some input from @kevmoo and the Dart team.

**Comment by pulyaevskiy** [comment]
Short update: it seems to work via `context` object with something like:

```dart
Firestore initFirestore(options) {
  context['FirebaseFirestore'] =
      context.callMethod('require', ['@google-cloud/firestore']);
  return new Firestore(options);
}
```

I can move forward with this, I guess. Though it would be nice to avoid this extra step somehow.

**Comment by CedX** [comment]
I also want this feature :) Currently, I'm using a helper function replacing the `require` one. It works but I'm not really satisfied with this solution.

```dart
@JS()
library firestore;

import 'dart:js_util';
import 'package:js/js.dart';

@JS('global')
external dynamic get global;

@JS('require')
external dynamic require(String id);

// Replaces the `require` function when you need to expose the exported classes.
T loadLibrary<T>(String identifier) {
  var module = require(identifier);
  var moduleId = '\$${identifier.replaceAll(new RegExp('[-/@.]'), '_')}'; // Hmm... :(
  if (!hasProperty(global, moduleId)) setProperty(global, moduleId, module);
  return module;
}

// Using the `moduleId` generated in the `loadLibrary` function as base name for @JS().
// For example: r'$events' for `EventEmitter` class, r'$http.Server', r'$stream.Readable'...
@JS(r'$_google_cloud_firestore')
class Firestore {
  external factory Firestore([options]);
}

main() {
  loadLibrary('@google-cloud/firestore');
  final firestore = new Firestore(/* options */);
}
```

**Comment by mbullington** [comment]
I'd really like to keep getPreamble() as minimal as possible, but as I saw looking through your library, you already use concatenation to add a shebang. If I added more functions, like my crude examples below, would that meet your usecases? @cedx @pulyaevskiy 

```
String getShebang() => "#!/usr/bin/env node";

String getModules(Map<String, String> modules) {
  String ret = "";
  modules.forEach((key, value) {
    ret += "self.${key} = require(\"${value}\"); \n";
  });
  return ret;
}
```

I may be getting ahead of myself, but potentially getModules could have a "lazy" parameter that uses ES6 proxies to lazy-load modules as well.

**Comment by pulyaevskiy** [comment]
Just a quick update: Since I was unblocked previously and had some success with proposed solution it’s not a critical issue for me at this point.

However I do think it would be nice to find a good generic solution for this issue.

I’ll be traveling for next few days but should be able to give it some thought time. Will post my updates here as soon as I can.

**Comment by CedX** [comment]
@mbullington For the shebang: it would be a useful addition. It's a very common practice to add a shebang to CLI scripts.

It could be a `bool` named parameter of the `getPreamble` function, associated to a read/write property for customizing it. Or the named parameter could also allow `String` values (question: with or without `#!` ?).

Here is how I'm currently using the preamble:
https://github.com/cedx/where.dart/blob/master/tool/grind.dart#L15

For the modules: we need lazy loading, just like real usages of the `require` function allows (i.e. it's not always used at top-level). It's a strong requirement from my POV.

Ideally, we should avoid polluting further the global namespace... but that would make the mapping between the `@JS` annotations and the modules complicated, so I don't think we can realistically avoid global namespace pollution.

The main problem I see with this issue: the preamble is used by the end applications, not by the libraries. So we need a common naming convention for `@JS` annotations, otherwise it could be very difficult for an application consuming (Node.js/npm)-based `pub` packages to setup the preamble properly.

As @pulyaevskiy said: we need to find a common generic solution. This may be beyond the scope of this issue: how various Dart wrappers of (Node.js/npm)-based libraries can coexist?

**Comment by pulyaevskiy** [comment]
A quick update here: I ended up removing namespaces in JS bindings for everything which is not truly global in Node, that is, any module loaded with `require` call. I'm using `@anonymous` classes throughout now, makes things a lot simpler. This also prevents collisions with other libraries.

Which means, it's actually not an issue for me at this point.

**Comment by mbullington** [comment]
@cedx Are using `@anonymous` classes something that you'd be able to implement for firestore? Are there any updates on this issue from your perspective?

**Comment by mbullington** [comment]
I'm going to close this issue due to inactivity, it's really good discussion but I still think that something like my getShebang/getModules example above would be the best solution if you wanted to put it in the preamble.

Since node_preamble doesn't provide any tooling of it's own, it just provides the preamble, adding other things such as shebangs and modules should be as easy as string concatenation. The additionalGlobals property could also be used, although that's more limited.

I may add the getShebang and getModules functions in the future.
